version: "3.9"

services:
  morai-noetic:
    build: .
    container_name: morai-noetic
    # 네트워킹: rosbridge와 MORAI 연동 편의를 위해 host 사용
    network_mode: host

    # GPU 사용 (NVIDIA Container Toolkit 필요)
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute

      # X11 Forwarding
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1

    # X 소켓 + MORAI 런처 폴더(읽기전용) 마운트
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/kante/Downloads/MoraiLauncher_Lin:/mnt/MoraiLauncher_Lin:ro
      # catkin_ws는 볼륨으로 유지(컨테이너 지워도 빌드 산출물 보존)
      - morai_catkin:/root/catkin_ws

    # 인터랙티브 사용 편의
    stdin_open: true
    tty: true

volumes:
  morai_catkin:
