origin_lat: 37.123456789
origin_lon: 126.987654321
origin_alt: 15.2
map_to_true_north_yaw_deg: 0.0   # 모르면 0부터 사용, 추후 보정
# 필요하면 GNSS, EGO 토픽 이름도 적어 두세요(런치에서 remap 가능)
ego_topic: /Ego_topic
gps_topic: /gps/fix
